### ISSUE TITLE
cpu_load.py No module named psutil

### ISSUE THREAD

**Issue by alexellis** [pimoroni/blinkt#14]
On Raspbian Lite after having run the curl sh. 

```
pi@blinkt1:~/Pimoroni/blinkt/examples $ python cpu_load.py
Traceback (most recent call last):
  File "cpu_load.py", line 6, in <module>
    import psutil
ImportError: No module named psutil
```

**Comment by alexellis** [comment]
```
Cpi@blinkt1:~/Pimoroni/blinkt/examples $ python mem_load.py
Traceback (most recent call last):
  File "mem_load.py", line 6, in <module>
    import psutil
ImportError: No module named psutil
```

**Comment by RogueM** [comment]
examples require extra modules, on an ad hoc basis. I have submitted PR #15 that should somewhat makes the process more friendly.

**Comment by wmurray-es** [comment]
Still seems to be an issue to this day when using the `sudo apt-get install pimoroni -y` method
